version: 2.1

jobs:
  test-job:
    docker:
      - image: cypress/included:7.1.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn cy:run --reporter cypress-circleci-reporter
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
      - store_test_results:
          path: test_results/cypress

workflows:
  test-wf:
    jobs:
      - test-job
